### ISSUE TITLE
Designing file structure outlines for back-end	

### ISSUE THREAD

**Issue by Bera0422** [bounswe/bounswe2023group9#263] opened 2023-10-10 18:40 UTC
### Issue Description

Designing file structure outlines for back-end
--

<br class="Apple-interchange-newline">

### Steps

- [ ] ...
- [ ] ...
- [ ] ...

**Comment by uyduranomer** [comment] 2023-10-12 21:04
There is another issue for the same task. This issue is a duplicate of #270 .
I am closing this issue...

**Closed by uyduranomer** 2023-10-12 21:04 UTC
Labels: duplicate
